run:
  timeout: 3m
  go: "1.25"

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gofmt
    - goimports

linters-settings:
  goimports:
    local-prefixes: github.com/dovgalb/project-rupor
  govet:
    enable-all: true

issues:
  exclude-use-default: false
