// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveInviteByCode = `-- name: GetActiveInviteByCode :one
SELECT id, room_id, code, created_by, created_at, revoked_at
FROM invites
WHERE code = $1 AND revoked_at IS NULL
`

func (q *Queries) GetActiveInviteByCode(ctx context.Context, code string) (Invite, error) {
	row := q.db.QueryRow(ctx, getActiveInviteByCode, code)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Code,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getActiveInviteByRoom = `-- name: GetActiveInviteByRoom :one
SELECT id, room_id, code, created_by, created_at, revoked_at
FROM invites
WHERE room_id = $1 AND revoked_at IS NULL
`

func (q *Queries) GetActiveInviteByRoom(ctx context.Context, roomID uuid.UUID) (Invite, error) {
	row := q.db.QueryRow(ctx, getActiveInviteByRoom, roomID)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Code,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertInvite = `-- name: InsertInvite :exec
INSERT INTO invites (id, room_id, code, created_by, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertInviteParams struct {
	ID        uuid.UUID
	RoomID    uuid.UUID
	Code      string
	CreatedBy uuid.UUID
	CreatedAt time.Time
}

func (q *Queries) InsertInvite(ctx context.Context, arg InsertInviteParams) error {
	_, err := q.db.Exec(ctx, insertInvite,
		arg.ID,
		arg.RoomID,
		arg.Code,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const revokeActiveInvitesByRoom = `-- name: RevokeActiveInvitesByRoom :execrows
UPDATE invites
SET revoked_at = $2
WHERE room_id = $1 AND revoked_at IS NULL
`

type RevokeActiveInvitesByRoomParams struct {
	RoomID    uuid.UUID
	RevokedAt pgtype.Timestamptz
}

func (q *Queries) RevokeActiveInvitesByRoom(ctx context.Context, arg RevokeActiveInvitesByRoomParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeActiveInvitesByRoom, arg.RoomID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
