// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID        uuid.UUID
	RoomID    uuid.UUID
	Name      string
	Kind      string
	CreatedAt time.Time
}

type Invite struct {
	ID        uuid.UUID
	RoomID    uuid.UUID
	Code      string
	CreatedBy uuid.UUID
	CreatedAt time.Time
	RevokedAt pgtype.Timestamptz
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	CreatedAt time.Time
	RevokedAt pgtype.Timestamptz
}

type Room struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Name      string
	CreatedAt time.Time
}

type RoomMember struct {
	RoomID   uuid.UUID
	UserID   uuid.UUID
	Role     string
	JoinedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Username     string
	CreatedAt    time.Time
}
