// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: room_members.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteRoomMember = `-- name: DeleteRoomMember :execrows
DELETE FROM room_members
WHERE room_id = $1 AND user_id = $2
`

type DeleteRoomMemberParams struct {
	RoomID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteRoomMember(ctx context.Context, arg DeleteRoomMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoomMember, arg.RoomID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRoomMember = `-- name: GetRoomMember :one
SELECT room_id, user_id, role, joined_at
FROM room_members
WHERE room_id = $1 AND user_id = $2
`

type GetRoomMemberParams struct {
	RoomID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetRoomMember(ctx context.Context, arg GetRoomMemberParams) (RoomMember, error) {
	row := q.db.QueryRow(ctx, getRoomMember, arg.RoomID, arg.UserID)
	var i RoomMember
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const insertRoomMember = `-- name: InsertRoomMember :exec
INSERT INTO room_members (room_id, user_id, role, joined_at)
VALUES ($1, $2, $3, $4)
`

type InsertRoomMemberParams struct {
	RoomID   uuid.UUID
	UserID   uuid.UUID
	Role     string
	JoinedAt time.Time
}

func (q *Queries) InsertRoomMember(ctx context.Context, arg InsertRoomMemberParams) error {
	_, err := q.db.Exec(ctx, insertRoomMember,
		arg.RoomID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	return err
}

const listRoomMembers = `-- name: ListRoomMembers :many
SELECT room_id, user_id, role, joined_at
FROM room_members
WHERE room_id = $1
ORDER BY joined_at ASC
`

func (q *Queries) ListRoomMembers(ctx context.Context, roomID uuid.UUID) ([]RoomMember, error) {
	rows, err := q.db.Query(ctx, listRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RoomMember
	for rows.Next() {
		var i RoomMember
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
