// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rooms.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteRoomByID = `-- name: DeleteRoomByID :execrows
DELETE FROM rooms
WHERE id = $1
`

func (q *Queries) DeleteRoomByID(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoomByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, owner_id, name, created_at
FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoomByID(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const insertRoom = `-- name: InsertRoom :exec
INSERT INTO rooms (id, owner_id, name, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertRoomParams struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Name      string
	CreatedAt time.Time
}

func (q *Queries) InsertRoom(ctx context.Context, arg InsertRoomParams) error {
	_, err := q.db.Exec(ctx, insertRoom,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.CreatedAt,
	)
	return err
}

const listRoomsByMember = `-- name: ListRoomsByMember :many
SELECT r.id, r.owner_id, r.name, r.created_at, m.role
FROM rooms r
JOIN room_members m ON m.room_id = r.id
WHERE m.user_id = $1
ORDER BY r.created_at DESC
`

type ListRoomsByMemberRow struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Name      string
	CreatedAt time.Time
	Role      string
}

func (q *Queries) ListRoomsByMember(ctx context.Context, userID uuid.UUID) ([]ListRoomsByMemberRow, error) {
	rows, err := q.db.Query(ctx, listRoomsByMember, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRoomsByMemberRow
	for rows.Next() {
		var i ListRoomsByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
