// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteChannelInRoom = `-- name: DeleteChannelInRoom :execrows
DELETE FROM channels
WHERE id = $1 AND room_id = $2
`

type DeleteChannelInRoomParams struct {
	ID     uuid.UUID
	RoomID uuid.UUID
}

func (q *Queries) DeleteChannelInRoom(ctx context.Context, arg DeleteChannelInRoomParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannelInRoom, arg.ID, arg.RoomID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertChannel = `-- name: InsertChannel :exec
INSERT INTO channels (id, room_id, name, kind, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertChannelParams struct {
	ID        uuid.UUID
	RoomID    uuid.UUID
	Name      string
	Kind      string
	CreatedAt time.Time
}

func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) error {
	_, err := q.db.Exec(ctx, insertChannel,
		arg.ID,
		arg.RoomID,
		arg.Name,
		arg.Kind,
		arg.CreatedAt,
	)
	return err
}

const listChannelsByRoom = `-- name: ListChannelsByRoom :many
SELECT id, room_id, name, kind, created_at
FROM channels
WHERE room_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListChannelsByRoom(ctx context.Context, roomID uuid.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listChannelsByRoom, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Name,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
