// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	CreatedAt time.Time
	RevokedAt pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Username     string
	CreatedAt    time.Time
}
