// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getChannelKind = `-- name: GetChannelKind :one
SELECT id, room_id, kind
FROM channels
WHERE id = $1
`

type GetChannelKindRow struct {
	ID     uuid.UUID
	RoomID uuid.UUID
	Kind   string
}

func (q *Queries) GetChannelKind(ctx context.Context, id uuid.UUID) (GetChannelKindRow, error) {
	row := q.db.QueryRow(ctx, getChannelKind, id)
	var i GetChannelKindRow
	err := row.Scan(&i.ID, &i.RoomID, &i.Kind)
	return i, err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, channel_id, author_id, text, created_at
FROM messages
WHERE id = $1
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.AuthorID,
		&i.Text,
		&i.CreatedAt,
	)
	return i, err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (id, channel_id, author_id, text, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertMessageParams struct {
	ID        uuid.UUID
	ChannelID uuid.UUID
	AuthorID  uuid.UUID
	Text      string
	CreatedAt time.Time
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.ID,
		arg.ChannelID,
		arg.AuthorID,
		arg.Text,
		arg.CreatedAt,
	)
	return err
}

const listMessagesBeforeCursor = `-- name: ListMessagesBeforeCursor :many
SELECT m.id, m.channel_id, m.author_id, m.text, m.created_at
FROM messages AS m
WHERE m.channel_id = $1
  AND (
    $2::uuid IS NULL
    OR (m.created_at, m.id) < (
        SELECT b.created_at, b.id FROM messages AS b WHERE b.id = $2
    )
  )
ORDER BY m.created_at DESC, m.id DESC
LIMIT $3::int
`

type ListMessagesBeforeCursorParams struct {
	ChannelID uuid.UUID
	BeforeID  pgtype.UUID
	Limit     int32
}

func (q *Queries) ListMessagesBeforeCursor(ctx context.Context, arg ListMessagesBeforeCursorParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesBeforeCursor, arg.ChannelID, arg.BeforeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.AuthorID,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
